# verify2.py
c = open(r"C:\Users\yaoli\lobsterai\project\中国翻译行业数据平台\index.html", "r", encoding="utf-8").read()
print("Size:", len(c), "bytes")
print("DOCTYPE:", c.startswith("<!DOCTYPE"))
print("Ends HTML:", c.strip().endswith("</html>"))
print("Watermarks:", c.count("风正起时制作"))
print("701.2亿:", "701.2亿" in c)
print("686.7万:", "686.7万" in c)
print("113.5万:", "113.5万" in c)
print("2183家:", "2183家" in c)
print("renderYear:", "renderYear" in c)
print("Company modals:", all(u in c for u in ["rws.com","transperfect.com","lionbridge.com","welocalize.com","gtcom.com.cn","transn.com","sunyu.com","cemachina.com","f.youdao.com","career.huawei.com"]))
print("Project sources:", all(u in c for u in ["genshin.hoyoverse.com","beijing2022.cn","heishenhua.com","tac-online.org.cn"]))
print("Recruit:", all(u in c for u in ["zhipin.com","liepin.com","zhaopin.com","51job.com"]))
print("Schools:", c.count("class=\"si\""))
print("Over 80KB:", len(c) >= 81920)
